#server:
#  port: ${PORT:8761}
#
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
#spring:
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8888
spring:
  application:
    name: demo-eureka-server
  zipkin:
    base-url: http://zipkin:9411
  #
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8888/eureka/
      register-with-eureka: false
      fetch-registry: false
  instance:
    hostname: localhost


  #spring.main.allow-bean-definition-overriding=true
  
  #spring.cloud.config.enabled=false
  #eureka.dashboard.path=/dashboard
  
  
  #zipkin properties
