server:
  port: 8083
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**

  #eureka-client-properties
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8888/eureka/

  #zipkin properties


  #api gate-way properties
  #this is for customer

#spring:
#  colud:
#    gateway:
#    routes.- id=customer
#spring.colud.gateway.routes.uri=lb://CUSTOMER
#spring.colud.gateway.routes.predicates.- path=/api/v1/customers/**

